wifi: !include wifi.yaml

captive_portal:

esphome:
  name: ${espname}
  platform: ESP8266
  board: esp8285

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret admin_password

