ssid: "Your Wifi Network"
password: !secret wifi_password
fast_connect: true
domain: .local
reboot_timeout: 0s

# Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: "${espname} Hotspot"
  password: !secret fallback_password

